### ISSUE TITLE
write back

### ISSUE THREAD

**Issue by davehun** [Yveaux/node-red-contrib-opentherm#2]
I would really like to pass back the otgw:

1. A room temperature
1. A room set point
1. An outside Temperature
1. Heating mode
do you think this would be hard?

**Comment by mikeS7** [comment]
I think the node is suitable to decode otgw/opentherm messages, to control the gateway you should pass [commands directly to the gateway](http://otgw.tclcode.com/firmware.html#configuration)

**Comment by Yveaux** [comment]
As @mikeS7 already indicated it currently is an OpenTerm decoder only. Sending messages is not supported, but could in principle be added.
Unfortunately I have other priorities; maybe someone else can submit a PR.
