### ISSUE TITLE
Illegal message length

### ISSUE THREAD

**Issue by BarBaar44** [Yveaux/node-red-contrib-opentherm#3]
Hi,

When setting this up in Node-Red, I receive an illegal message length error. Any idea what this may be?

Sample output:
`BC0110000
T00110000
BC0110000
T90395500
B50395500
T90395500
B50395500
T90101300
B50101300
T90101300
B50101300
T10181328
BF0180000
T10181328
BF0180000
T10010000
BD0010000
T100E0000
`

`[{"id":"3b45b0ce.7cf28","type":"tcp in","z":"d4384ba4.7c6168","name":"","server":"client","host":"192.168.0.140","port":"23","datamode":"stream","datatype":"buffer","newline":"","topic":"","base64":false,"x":100,"y":620,"wires":[["43b56453.5a750c","4d1bc8df.60e278"]]},{"id":"43b56453.5a750c","type":"otgwdec","z":"d4384ba4.7c6168","name":"","x":405,"y":607,"wires":[["e6adfb8.ec37e08","87140a64.86d298"]]},{"id":"87140a64.86d298","type":"switch","z":"d4384ba4.7c6168","name":"read ack/write ack/else","property":"msgtype","propertyType":"msg","rules":[{"t":"eq","v":"4","vt":"num"},{"t":"eq","v":"5","vt":"num"},{"t":"else"}],"checkall":"true","repair":false,"outputs":3,"x":633,"y":607,"wires":[["fcd8c46e.1eab78"],["fcd8c46e.1eab78"],[]]},{"id":"e6adfb8.ec37e08","type":"debug","z":"d4384ba4.7c6168","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":579,"y":672,"wires":[]},{"id":"4d1bc8df.60e278","type":"debug","z":"d4384ba4.7c6168","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":440,"y":680,"wires":[]},{"id":"8c002377.64cf1","type":"function","z":"d4384ba4.7c6168","name":"To CSV","func":"msg.payload =         msg.raw\n              + \",\" + msg.msgtype\n              + \",\" + msg.dataid\n              + \",\" + msg.datavalue\n              + \",\" + msg.topic\n              + \",\" + msg.payload;\nreturn msg;","outputs":1,"noerr":0,"x":1093,"y":602,"wires":[["391280ea.61294"]]},{"id":"fcd8c46e.1eab78","type":"openthermdec","z":"d4384ba4.7c6168","name":"","x":880,"y":600,"wires":[["96228059.1c16a","8c002377.64cf1"]]},{"id":"96228059.1c16a","type":"debug","z":"d4384ba4.7c6168","name":"","active":false,"console":"false","complete":"true","x":1050,"y":666,"wires":[]},{"id":"391280ea.61294","type":"file","z":"d4384ba4.7c6168","name":"","filename":"/opentherm.log","appendNewline":true,"createDir":true,"overwriteFile":"false","x":1271,"y":602,"wires":[[]]}]`

**Comment by Yveaux** [comment]
The messages need to be separated on space before passing them to the opentherm node.
